version: '3'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./app:/usr/src/app
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: 'adminuser'
    #   MONGO_INITDB_ROOT_PASSWORD: '123456'
    volumes:
      - ./docker/mongo-volume:/data/db
    ports: 
      - "27017:27017"